### PR TITLE
Default values from environment variables

### PR DESCRIPTION
**Pull request by mattn**
If user set some PGXXX environment variable which is same as pgsql, use it on pome.

### CODE REVIEW

**Comment by rach** [comment]
Thanks a lot for this PR
I manually fastforward merged your PR with develop with your authorship
https://github.com/rach/pome/commit/c5e7fdaa1ffef44754e947e04a54558fd2e4f849

It's something that I really wanted to add. Do you know where I can find the list of all the envar supported by psql?

**Comment by rach** [comment]
Btw, the reason why I merged it with develop is to avoid that people get last changes when running `go get` and so having only release version in master. 
Looking forward for your next PR :)

**Comment by mattn** [comment]
list of environment variables is here: http://www.postgresql.org/docs/9.1/static/libpq-envars.html

but i'm not sure which is used for pgsql.

**Comment by rach** [comment]
Thanks a lot for the link. I will keep that in mind with future flags

**Pull request closed without merging**
